# Stage1
FROM gradle:jdk25 AS build

COPY --chown=gradle:gradle . /home/gradle/src

WORKDIR /home/gradle/src

RUN gradle build -x test --no-daemon

# Stage 2
FROM eclipse-temurin:25-jre-alpine

RUN mkdir /app

COPY --from=build  /home/gradle/src/build/libs/*.jar /app/cinema-backend.jar

EXPOSE 8080

ENTRYPOINT [ "java","-jar","/app/cinema-backend.jar" ]