spring:

  spring:
  datasource:
    url: dpg-d912t07avr4c739664r0-a:5432/cinema_backend_db
    username: mycinema_backend_db_useruser
    password: LEG7N6Z6WmfeSo5XZPkLgcZwtspyIL62
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
      separator: "^;"

  application:
    name: cinema-backend

  ai:
    openai:
      api-key: ${OPENAI_API_KEY:default_key}

app:
  jwtSecret: "vTq9zKpL4mXr7Qw2Nd8HsF6UaYcE1JgP5bR3ZxC0uMiDoWlA9BnSfGhKt"
  jwtExpirationMs: 3600000