spring:

  spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  application:
    name: cinema-backend

  ai:
    openai:
      api-key: ${OPENAI_API_KEY:default_key}

app:
  jwtSecret: "vTq9zKpL4mXr7Qw2Nd8HsF6UaYcE1JgP5bR3ZxC0uMiDoWlA9BnSfGhKt"
  jwtExpirationMs: 3600000

  