-- Seeds genres, 50 real movies, and their many-to-many links.
-- Idempotent: the DO block bails out if any movie already exists.
-- Duration is stored as nanoseconds (Hibernate 6 default mapping for java.time.Duration).

DO
$$
    BEGIN
        IF EXISTS (SELECT 1 FROM movies LIMIT 1) THEN
            RETURN;
        END IF;

        -- Legacy tables created with @GeneratedValue(AUTO) have no DB-level default on id.
        -- Hibernate's ddl-auto=update won't retrofit identity onto an existing column,
        -- so we patch it here on first seed.
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'movies'
              AND column_name = 'id'
              AND is_identity = 'YES'
        ) THEN
            ALTER TABLE movies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
        END IF;

        INSERT INTO genres (name) VALUES
            ('Drama'), ('Crime'), ('Action'), ('Sci-Fi'), ('Thriller'),
            ('Adventure'), ('Romance'), ('Animation'), ('Fantasy'), ('Biography'),
            ('Comedy'), ('Mystery'), ('War'), ('Western'), ('Horror'), ('Family');

        INSERT INTO movies (name, description, duration, rating) VALUES
            ('The Shawshank Redemption', 'Two imprisoned men bond over years, finding solace and redemption through acts of common decency.', 142 * 60 * 1000000000::bigint, 9),
            ('The Godfather', 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.', 175 * 60 * 1000000000::bigint, 9),
            ('The Dark Knight', 'Batman faces the Joker, a criminal mastermind who unleashes chaos on the people of Gotham.', 152 * 60 * 1000000000::bigint, 9),
            ('The Godfather Part II', 'The early life of Vito Corleone is intercut with the rise of his son Michael as the new Don.', 202 * 60 * 1000000000::bigint, 9),
            ('12 Angry Men', 'A jury holdout pushes his fellow jurors to reconsider the evidence in a capital murder case.', 96 * 60 * 1000000000::bigint, 9),
            ('Schindler''s List', 'In German-occupied Poland, industrialist Oskar Schindler saves over a thousand Jewish refugees from the Nazis.', 195 * 60 * 1000000000::bigint, 9),
            ('The Lord of the Rings: The Return of the King', 'Gandalf and Aragorn lead the World of Men against Sauron''s army to draw his gaze from Frodo and Sam.', 201 * 60 * 1000000000::bigint, 9),
            ('Pulp Fiction', 'The lives of two mob hitmen, a boxer, and a gangster''s wife intertwine in four tales of violence and redemption.', 154 * 60 * 1000000000::bigint, 9),
            ('The Lord of the Rings: The Fellowship of the Ring', 'A hobbit and eight companions set out to destroy a powerful ring and save Middle-earth from the Dark Lord.', 178 * 60 * 1000000000::bigint, 9),
            ('The Good, the Bad and the Ugly', 'A bounty-hunting scam joins two men in an uneasy alliance against a third in a race to find buried Confederate gold.', 178 * 60 * 1000000000::bigint, 9),
            ('Forrest Gump', 'Decades of American history unfold from the perspective of a slow-witted but kind-hearted Alabama man.', 142 * 60 * 1000000000::bigint, 9),
            ('Fight Club', 'An insomniac office worker and a soap salesman form an underground fight club that spirals out of control.', 139 * 60 * 1000000000::bigint, 8),
            ('Inception', 'A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea.', 148 * 60 * 1000000000::bigint, 9),
            ('The Lord of the Rings: The Two Towers', 'The fellowship is broken; Frodo and Sam press toward Mordor as Aragorn rallies Rohan against Saruman.', 179 * 60 * 1000000000::bigint, 9),
            ('Star Wars: Episode V - The Empire Strikes Back', 'After the Rebels are overpowered, Luke begins Jedi training with Yoda while his friends are pursued by Vader.', 124 * 60 * 1000000000::bigint, 9),
            ('The Matrix', 'A computer hacker learns about the true nature of reality and his role in the war against its controllers.', 136 * 60 * 1000000000::bigint, 9),
            ('Goodfellas', 'The story of Henry Hill and his life in the mob, covering his relationship with his wife and his mob partners.', 145 * 60 * 1000000000::bigint, 9),
            ('One Flew Over the Cuckoo''s Nest', 'A criminal pleads insanity to avoid prison and ends up clashing with a tyrannical nurse at a mental institution.', 133 * 60 * 1000000000::bigint, 9),
            ('Se7en', 'Two detectives hunt a serial killer who uses the seven deadly sins as the motifs for his murders.', 127 * 60 * 1000000000::bigint, 8),
            ('Seven Samurai', 'A poor village hires seven masterless samurai to defend it from bandits who return every harvest.', 207 * 60 * 1000000000::bigint, 9),
            ('It''s a Wonderful Life', 'An angel shows a frustrated businessman what life would have been like if he had never existed.', 130 * 60 * 1000000000::bigint, 8),
            ('The Silence of the Lambs', 'A young FBI cadet seeks the help of a cannibalistic killer to catch another serial murderer.', 118 * 60 * 1000000000::bigint, 8),
            ('City of God', 'Two boys growing up in a violent Rio favela take very different paths through crime and journalism.', 130 * 60 * 1000000000::bigint, 8),
            ('Saving Private Ryan', 'A group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.', 169 * 60 * 1000000000::bigint, 8),
            ('Interstellar', 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity''s survival.', 169 * 60 * 1000000000::bigint, 9),
            ('Spirited Away', 'A sullen ten-year-old girl wanders into a world ruled by gods and witches where humans are turned into beasts.', 125 * 60 * 1000000000::bigint, 9),
            ('The Green Mile', 'The lives of guards on Death Row are affected by one of their charges: a black man accused of murder who has a mysterious gift.', 189 * 60 * 1000000000::bigint, 8),
            ('Life Is Beautiful', 'A Jewish father uses his fertile imagination to shield his son from the horrors of a Nazi concentration camp.', 116 * 60 * 1000000000::bigint, 8),
            ('Star Wars: Episode IV - A New Hope', 'Luke Skywalker joins forces with rebels to rescue Princess Leia and destroy the Empire''s Death Star.', 121 * 60 * 1000000000::bigint, 8),
            ('Terminator 2: Judgment Day', 'A reprogrammed Terminator is sent back to protect a young John Connor from a more advanced killing machine.', 137 * 60 * 1000000000::bigint, 8),
            ('Back to the Future', 'A teenager is accidentally sent thirty years into the past in a time-traveling DeLorean built by an eccentric scientist.', 116 * 60 * 1000000000::bigint, 8),
            ('The Pianist', 'A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto during World War II.', 150 * 60 * 1000000000::bigint, 8),
            ('Psycho', 'A secretary on the run checks into a remote motel run by a young man under the domination of his mother.', 109 * 60 * 1000000000::bigint, 8),
            ('Léon: The Professional', 'A reclusive hitman takes in a twelve-year-old girl after her family is murdered by a corrupt DEA agent.', 110 * 60 * 1000000000::bigint, 8),
            ('Gladiator', 'A former Roman general sets out to exact vengeance against the corrupt emperor who murdered his family.', 155 * 60 * 1000000000::bigint, 8),
            ('The Departed', 'An undercover cop and a mole in the police try to identify each other while infiltrating an Irish gang in Boston.', 151 * 60 * 1000000000::bigint, 8),
            ('Whiplash', 'A promising young drummer enrolls at a cut-throat music conservatory where his teacher will stop at nothing to push him.', 106 * 60 * 1000000000::bigint, 8),
            ('The Prestige', 'After a tragic accident, two stage magicians in 1890s London engage in a battle to create the ultimate illusion.', 130 * 60 * 1000000000::bigint, 8),
            ('Casablanca', 'A cynical expatriate American cafe owner struggles to decide whether or not to help his former lover and her husband escape the Nazis.', 102 * 60 * 1000000000::bigint, 8),
            ('The Lion King', 'After the murder of his father, a young lion prince flees his kingdom only to learn the true meaning of responsibility.', 88 * 60 * 1000000000::bigint, 8),
            ('Apocalypse Now', 'A U.S. Army officer is sent on a dangerous mission into Cambodia to assassinate a renegade Special Forces Colonel.', 147 * 60 * 1000000000::bigint, 8),
            ('Alien', 'The crew of a commercial spacecraft encounter a deadly lifeform after investigating a mysterious transmission.', 117 * 60 * 1000000000::bigint, 8),
            ('Memento', 'A man with short-term memory loss attempts to track down his wife''s murderer using notes and tattoos.', 113 * 60 * 1000000000::bigint, 8),
            ('American History X', 'A former neo-Nazi tries to prevent his younger brother from going down the same destructive path.', 119 * 60 * 1000000000::bigint, 8),
            ('Django Unchained', 'With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.', 165 * 60 * 1000000000::bigint, 8),
            ('WALL-E', 'In the distant future, a small waste-collecting robot inadvertently embarks on a journey that will decide humanity''s fate.', 98 * 60 * 1000000000::bigint, 8),
            ('The Shining', 'A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence.', 146 * 60 * 1000000000::bigint, 8),
            ('Coco', 'A young boy is accidentally transported to the Land of the Dead, where he seeks the help of his deceased musician great-great-grandfather.', 105 * 60 * 1000000000::bigint, 8),
            ('Parasite', 'Greed and class discrimination threaten the newly formed symbiotic relationship between two families.', 132 * 60 * 1000000000::bigint, 9),
            ('Avengers: Endgame', 'After the devastating events of Infinity War, the Avengers assemble once more to reverse Thanos''s actions.', 181 * 60 * 1000000000::bigint, 8);

        INSERT INTO movies_genres (movie_id, genre_id)
        SELECT m.id, g.id
        FROM (VALUES
            ('The Shawshank Redemption', 'Drama'),
            ('The Godfather', 'Crime'), ('The Godfather', 'Drama'),
            ('The Dark Knight', 'Action'), ('The Dark Knight', 'Crime'), ('The Dark Knight', 'Drama'),
            ('The Godfather Part II', 'Crime'), ('The Godfather Part II', 'Drama'),
            ('12 Angry Men', 'Crime'), ('12 Angry Men', 'Drama'),
            ('Schindler''s List', 'Biography'), ('Schindler''s List', 'Drama'), ('Schindler''s List', 'War'),
            ('The Lord of the Rings: The Return of the King', 'Adventure'), ('The Lord of the Rings: The Return of the King', 'Drama'), ('The Lord of the Rings: The Return of the King', 'Fantasy'),
            ('Pulp Fiction', 'Crime'), ('Pulp Fiction', 'Drama'),
            ('The Lord of the Rings: The Fellowship of the Ring', 'Adventure'), ('The Lord of the Rings: The Fellowship of the Ring', 'Drama'), ('The Lord of the Rings: The Fellowship of the Ring', 'Fantasy'),
            ('The Good, the Bad and the Ugly', 'Adventure'), ('The Good, the Bad and the Ugly', 'Western'),
            ('Forrest Gump', 'Drama'), ('Forrest Gump', 'Romance'),
            ('Fight Club', 'Drama'),
            ('Inception', 'Action'), ('Inception', 'Adventure'), ('Inception', 'Sci-Fi'),
            ('The Lord of the Rings: The Two Towers', 'Adventure'), ('The Lord of the Rings: The Two Towers', 'Drama'), ('The Lord of the Rings: The Two Towers', 'Fantasy'),
            ('Star Wars: Episode V - The Empire Strikes Back', 'Action'), ('Star Wars: Episode V - The Empire Strikes Back', 'Adventure'), ('Star Wars: Episode V - The Empire Strikes Back', 'Fantasy'),
            ('The Matrix', 'Action'), ('The Matrix', 'Sci-Fi'),
            ('Goodfellas', 'Biography'), ('Goodfellas', 'Crime'), ('Goodfellas', 'Drama'),
            ('One Flew Over the Cuckoo''s Nest', 'Drama'),
            ('Se7en', 'Crime'), ('Se7en', 'Drama'), ('Se7en', 'Mystery'),
            ('Seven Samurai', 'Action'), ('Seven Samurai', 'Adventure'), ('Seven Samurai', 'Drama'),
            ('It''s a Wonderful Life', 'Drama'), ('It''s a Wonderful Life', 'Fantasy'), ('It''s a Wonderful Life', 'Romance'),
            ('The Silence of the Lambs', 'Crime'), ('The Silence of the Lambs', 'Drama'), ('The Silence of the Lambs', 'Thriller'),
            ('City of God', 'Crime'), ('City of God', 'Drama'),
            ('Saving Private Ryan', 'Drama'), ('Saving Private Ryan', 'War'),
            ('Interstellar', 'Adventure'), ('Interstellar', 'Drama'), ('Interstellar', 'Sci-Fi'),
            ('Spirited Away', 'Animation'), ('Spirited Away', 'Adventure'), ('Spirited Away', 'Fantasy'),
            ('The Green Mile', 'Crime'), ('The Green Mile', 'Drama'), ('The Green Mile', 'Fantasy'),
            ('Life Is Beautiful', 'Comedy'), ('Life Is Beautiful', 'Drama'), ('Life Is Beautiful', 'Romance'),
            ('Star Wars: Episode IV - A New Hope', 'Action'), ('Star Wars: Episode IV - A New Hope', 'Adventure'), ('Star Wars: Episode IV - A New Hope', 'Fantasy'),
            ('Terminator 2: Judgment Day', 'Action'), ('Terminator 2: Judgment Day', 'Sci-Fi'),
            ('Back to the Future', 'Adventure'), ('Back to the Future', 'Comedy'), ('Back to the Future', 'Sci-Fi'),
            ('The Pianist', 'Biography'), ('The Pianist', 'Drama'), ('The Pianist', 'War'),
            ('Psycho', 'Horror'), ('Psycho', 'Mystery'), ('Psycho', 'Thriller'),
            ('Léon: The Professional', 'Action'), ('Léon: The Professional', 'Crime'), ('Léon: The Professional', 'Drama'),
            ('Gladiator', 'Action'), ('Gladiator', 'Adventure'), ('Gladiator', 'Drama'),
            ('The Departed', 'Crime'), ('The Departed', 'Drama'), ('The Departed', 'Thriller'),
            ('Whiplash', 'Drama'),
            ('The Prestige', 'Drama'), ('The Prestige', 'Mystery'), ('The Prestige', 'Thriller'),
            ('Casablanca', 'Drama'), ('Casablanca', 'Romance'), ('Casablanca', 'War'),
            ('The Lion King', 'Animation'), ('The Lion King', 'Adventure'), ('The Lion King', 'Drama'),
            ('Apocalypse Now', 'Drama'), ('Apocalypse Now', 'Mystery'), ('Apocalypse Now', 'War'),
            ('Alien', 'Horror'), ('Alien', 'Sci-Fi'),
            ('Memento', 'Mystery'), ('Memento', 'Thriller'),
            ('American History X', 'Drama'),
            ('Django Unchained', 'Drama'), ('Django Unchained', 'Western'),
            ('WALL-E', 'Animation'), ('WALL-E', 'Adventure'), ('WALL-E', 'Family'),
            ('The Shining', 'Drama'), ('The Shining', 'Horror'),
            ('Coco', 'Animation'), ('Coco', 'Adventure'), ('Coco', 'Family'),
            ('Parasite', 'Drama'), ('Parasite', 'Thriller'),
            ('Avengers: Endgame', 'Action'), ('Avengers: Endgame', 'Adventure'), ('Avengers: Endgame', 'Drama')
        ) AS v(movie_name, genre_name)
        JOIN movies m ON m.name = v.movie_name
        JOIN genres g ON g.name = v.genre_name;

    END
$$
^;
